/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Bot, Shield, Cpu, Activity, Mail, CheckCircle2, ChevronRight, HelpCircle, ArrowRight, Zap, RefreshCw, Layers } from 'lucide-react';
import vincorpLogo from '../assets/images/vincorp_logo.png';
import { Logo } from './common/Logo';
import { Navbar } from './Navbar';

interface LandingPageProps {
  onNavigate: (route: string) => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onNavigate }) => {
  const [activeFaq, setActiveFaq] = useState<number | null>(null);
  const [contactForm, setContactForm] = useState({ name: '', email: '', message: '' });
  const [contactSuccess, setContactSuccess] = useState(false);
  const [showCookieConsent, setShowCookieConsent] = useState(() => !localStorage.getItem('vinebot_cookie_consent'));
  const [showCookieSettingsInfo, setShowCookieSettingsInfo] = useState(false);

  const handleAcceptCookies = () => {
    localStorage.setItem('vinebot_cookie_consent', 'accepted');
    setShowCookieConsent(false);
  };

  const toggleFaq = (index: number) => {
    setActiveFaq(activeFaq === index ? null : index);
  };

  const handleContactSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!contactForm.name || !contactForm.email || !contactForm.message) return;
    setContactSuccess(true);
    setContactForm({ name: '', email: '', message: '' });
    setTimeout(() => setContactSuccess(false), 5000);
  };

  const features = [
    {
      icon: <Shield className="w-6 h-6 text-emerald-400" />,
      title: "AES-256-GCM Cryptographic Vault",
      description: "Your MetaTrader 5 login credentials are double encrypted at the database layer. No cleartext credentials ever enter runtime logs or network caches."
    },
    {
      icon: <Cpu className="w-6 h-6 text-indigo-400" />,
      title: "Automated VPS Execution",
      description: "Our bot team provisions a dedicated, low-latency Windows Server instance to host and run your specialized expert advisor bot, running 24/5."
    },
    {
      icon: <Activity className="w-6 h-6 text-purple-400" />,
      title: "Intelligent Parameter Management",
      description: "The trading algorithms dynamically monitor drawdown levels and use tight trailing stops to secure equity without user manual interventions."
    },
    {
      icon: <Layers className="w-6 h-6 text-amber-400" />,
      title: "Enterprise Status Tracking",
      description: "Observe real-time activation updates through our step-by-step terminal progression timeline, keeping you fully appraised of VPS state changes."
    }
  ];

  const pricingPlans = [
    {
      name: "Vinebot Pro Access",
      price: 100,
      subLabel: null,
      interval: "mo",
      badge: "ACTIVE AUTOMATED EA LICENSE",
      description: "Complete automated MetaTrader 5 (MT5) bot access. Includes low-latency server allocation, automated expert execution, and dedicated risk trailing management.",
      features: [
        "Up to 3 Linked MT5 Accounts",
        "Advanced Drawdown Limit Safeguards",
        "Dedicated VPS Hosting Included",
        "Low-Latency Server Node Allocation",
        "Standard Support"
      ],
      popular: false,
      buttonText: "Get Started"
    },
    {
      name: "Vinebot VIP Unlimited",
      price: 200,
      subLabel: "+ 20% Profit Share",
      interval: "mo",
      badge: "MOST POPULAR / VIP",
      description: "Unlimited automated MetaTrader 5 bot access. Requires a 20% monthly profit-sharing fee on trading profits generated by the EA.",
      features: [
        "Unlimited Linked MT5 Accounts",
        "Custom High-Frequency Bot Strategies",
        "High-Priority Dedicated VPS Instance",
        "20% Monthly Profit Share Agreement",
        "1-on-1 VIP Setup & Telegram Priority Support"
      ],
      popular: true,
      buttonText: "Get VIP Access"
    }
  ];

  const faqs = [
    {
      q: "What is Vinebot and how does it execute trades?",
      a: "Vinebot is an automated trading-as-a-service (TaaS) software platform. Once you register, purchase a subscription, and input your MT5 details, our expert server administration team hosts and configures a private Expert Advisor (EA) bot on low-latency virtual servers to run on your behalf. You don't have to download any files or leave your computer running."
    },
    {
      q: "Can I control the trading bot's parameters or pairs directly?",
      a: "No. Vinebot is fully automated and parameters are carefully structured, updated, and deployed by our team of quantitative trade developers. This protects subscribers from excessive leverage or high-drawdown errors typical of manual bot configurations."
    },
    {
      q: "How secure are my MetaTrader 5 connection credentials?",
      a: "We prioritize security above all else. Your MT5 account passwords are encrypted using AES-256-GCM. The encryption key resides in a secure server-only vault. Plaintext passwords are never returned in standard client API payloads, safeguarding your broker integrity."
    },
    {
      q: "Can I cancel my subscription or remove my MT5 account at any time?",
      a: "Yes. You can manage and schedule subscription cancellations directly from your Billing tab. If you unlink or delete your MT5 credentials from your profile, our bot server instantly destroys the deployment files and uninstalls the bot execution routine."
    }
  ];

  return (
    <div className="bg-[#0b0d12] text-gray-200 min-h-screen font-sans relative overflow-hidden" id="landing-page">
      {/* Background Watermark */}
      <div 
        className="fixed inset-0 pointer-events-none flex items-center justify-center z-0 opacity-[0.03] grayscale filter select-none"
        style={{
          backgroundImage: `url(${vincorpLogo})`,
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          backgroundSize: 'contain',
          maxWidth: '75%',
          maxHeight: '75%',
          margin: 'auto',
        }}
      />

      {/* Navbar Header */}
      <Navbar onNavigate={onNavigate} />

      {/* Hero Section */}
      <motion.section 
        initial={{ opacity: 0, y: 25 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="relative overflow-hidden py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto flex flex-col items-center text-center"
      >
        {/* Glow effects */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-indigo-600/10 blur-[120px] rounded-full -z-10" />
        <div className="absolute top-1/2 left-1/3 -translate-y-1/2 w-[300px] h-[300px] bg-emerald-600/5 blur-[100px] rounded-full -z-10" />

        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#1b202e]/60 border border-[#2d3849]/50 text-indigo-400 text-xs font-semibold mb-6">
          <Zap className="w-3.5 h-3.5 animate-pulse" /> Automated MT5 Expert Bot Platform
        </div>

        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-white max-w-4xl leading-tight sm:leading-none">
          Automated MetaTrader Bot <span className="bg-gradient-to-r from-indigo-400 via-purple-400 to-emerald-400 bg-clip-text text-transparent">Deployment & VPS Hosting</span>
        </h1>

        <p className="mt-6 text-lg sm:text-xl text-gray-400 max-w-3xl leading-relaxed">
          Link your MT5 credentials securely using premium AES-256-GCM encryption. Our operations team provisions, secures, and maintains low-latency cloud servers running elite algorithms for you.
        </p>

        <div className="mt-10 flex flex-col sm:flex-row items-center gap-4 justify-center">
          <button 
            id="hero-start-btn"
            onClick={() => onNavigate('/register')}
            className="w-full sm:w-auto px-8 py-3.5 bg-indigo-600 text-white font-medium rounded-lg hover:bg-indigo-500 transition-colors shadow-xl shadow-indigo-600/20 flex items-center justify-center gap-2 cursor-pointer"
          >
            Create Your Account <ArrowRight className="w-4 h-4" />
          </button>
          <a 
            href="#pricing"
            className="w-full sm:w-auto px-8 py-3.5 bg-[#151922] text-gray-300 font-medium rounded-lg border border-[#232a39] hover:border-[#2f394d] hover:bg-[#1a202c] transition-colors text-center cursor-pointer"
          >
            View Pricing Packages
          </a>
        </div>

        {/* Dynamic status line to avoid "AI Slop" but feel premium */}
        <div className="mt-16 flex items-center gap-8 justify-center flex-wrap text-sm text-gray-500 font-medium border-t border-[#1b202e]/60 pt-8 w-full max-w-3xl">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>AES-256 Secured Credentials</span>
          </div>
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-indigo-400" />
            <span>Dedicated VPS Servers</span>
          </div>
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-purple-400" />
            <span>24/5 Live Signal Execution</span>
          </div>
        </div>
      </motion.section>

      {/* Features Section */}
      <section id="features" className="py-20 bg-[#080a0e] border-y border-[#121620]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div 
            initial={{ opacity: 0, y: 25 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-50px" }}
            transition={{ duration: 0.5 }}
            className="text-center max-w-3xl mx-auto"
          >
            <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
              Engineered for absolute server safety & precision
            </h2>
            <p className="mt-4 text-gray-400 text-base">
              Unlike typical black-box bots, Vinebot provides strict, structured parameters deployed manually on dedicated containers, minimizing slippage and maximizing risk discipline.
            </p>
          </motion.div>

          <div className="mt-16 grid grid-cols-1 md:grid-cols-2 gap-8">
            {features.map((f, i) => (
              <motion.div 
                key={i} 
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="bg-[#0e1118] border border-[#1b202e] rounded-xl p-6 hover:border-[#2d3849] hover:bg-[#11151f] transition-all duration-300 shadow-sm"
              >
                <div className="w-12 h-12 bg-[#171c2a] rounded-lg flex items-center justify-center mb-4 border border-[#232b3f]">
                  {f.icon}
                </div>
                <h3 className="text-lg font-semibold text-white mb-2">{f.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed">{f.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <motion.div 
          initial={{ opacity: 0, y: 25 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.5 }}
          className="text-center max-w-3xl mx-auto mb-16"
        >
          <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Select an elite subscription package
          </h2>
          <p className="mt-4 text-gray-400">
            No long contracts, cancel at any time. Bot activation processes within hours of subscription.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-5xl mx-auto">
          {pricingPlans.map((plan, i) => (
            <motion.div 
              key={i} 
              initial={{ opacity: 0, y: 35 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.5, delay: i * 0.15 }}
              className={`bg-[#0d1017] border rounded-2xl p-8 flex flex-col justify-between relative transition-all duration-300 w-full ${
                plan.popular 
                  ? 'border-indigo-500/80 shadow-2xl shadow-indigo-500/10 bg-gradient-to-b from-[#121524] to-[#0d1017]' 
                  : 'border-[#1b202e] hover:border-[#2d3849]'
              }`}
            >
              <span className={`absolute -top-3.5 left-1/2 -translate-x-1/2 px-3.5 py-1 text-[10px] font-extrabold rounded-full tracking-wider uppercase whitespace-nowrap shadow-md ${
                plan.popular 
                  ? 'bg-gradient-to-r from-indigo-500 via-purple-500 to-amber-500 text-white shadow-indigo-500/20' 
                  : 'bg-[#151a24] border border-[#2d3849] text-indigo-300'
              }`}>
                {plan.badge}
              </span>

              <div>
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-xl font-bold text-white">{plan.name}</h3>
                  {plan.popular && (
                    <span className="text-amber-400 bg-amber-400/10 border border-amber-400/20 text-[10px] font-bold px-2 py-0.5 rounded uppercase">VIP</span>
                  )}
                </div>
                
                <p className="text-gray-400 text-xs leading-relaxed mb-6 min-h-[40px]">{plan.description}</p>
                
                <div className="flex items-baseline flex-wrap gap-2 mb-6 bg-[#080a0e] p-4 rounded-xl border border-[#1b202e]">
                  <span className="text-4xl font-extrabold text-white">${plan.price}</span>
                  <span className="text-gray-400 text-sm">/ {plan.interval}</span>
                  {plan.subLabel && (
                    <span className="ml-auto text-xs font-bold text-amber-400 bg-amber-500/10 px-2.5 py-1 rounded-md border border-amber-500/20">
                      {plan.subLabel}
                    </span>
                  )}
                </div>

                <ul className="space-y-3.5 border-t border-[#1b202e] pt-6">
                  {plan.features.map((feat, idx) => (
                    <li key={idx} className="flex items-start gap-2.5 text-xs text-gray-300">
                      <CheckCircle2 className={`w-4 h-4 shrink-0 mt-0.5 ${plan.popular ? 'text-amber-400' : 'text-indigo-400'}`} />
                      <span>{feat}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <button 
                id={`plan-subscribe-${i}`}
                onClick={() => onNavigate('/register')}
                className={`mt-8 w-full py-3.5 rounded-lg text-xs font-bold tracking-wider uppercase transition-all flex items-center justify-center gap-2 cursor-pointer ${
                  plan.popular 
                    ? 'bg-gradient-to-r from-indigo-600 via-purple-600 to-indigo-600 hover:from-indigo-500 hover:to-purple-500 text-white shadow-lg shadow-indigo-600/25' 
                    : 'bg-[#151a24] text-gray-200 border border-[#232c3d] hover:bg-[#1a202d] hover:text-white'
                }`}
              >
                {plan.buttonText} <ChevronRight className="w-4 h-4" />
              </button>
            </motion.div>
          ))}
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="py-20 bg-[#080a0e] border-t border-[#121620]">
        <motion.div 
          initial={{ opacity: 0, y: 25 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.5 }}
          className="max-w-4xl mx-auto px-4 sm:px-6"
        >
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold tracking-tight text-white">Frequently Asked Questions</h2>
            <p className="text-gray-400 text-sm mt-2">Find clarity on our billing, security protocols, and platform architecture.</p>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div 
                key={idx} 
                className="bg-[#0e1118] border border-[#1b202e] rounded-xl overflow-hidden transition-all"
              >
                <button 
                  onClick={() => toggleFaq(idx)}
                  className="w-full text-left p-5 flex items-center justify-between text-white font-medium hover:bg-[#111520] transition-colors gap-4"
                >
                  <span className="text-sm sm:text-base flex items-center gap-2.5">
                    <HelpCircle className="w-5 h-5 text-indigo-400 shrink-0" />
                    {faq.q}
                  </span>
                  <span className="text-indigo-400 shrink-0 text-xl font-bold">
                    {activeFaq === idx ? '-' : '+'}
                  </span>
                </button>
                {activeFaq === idx && (
                  <div className="p-5 border-t border-[#1b202e] bg-[#0c0e14] text-sm text-gray-400 leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </motion.div>
      </section>

      {/* Contact Section */}
      <section id="contact" className="py-24 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
        <motion.div 
          initial={{ opacity: 0, y: 25 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.5 }}
          className="bg-[#0e1118] border border-[#1b202e] rounded-2xl p-8 sm:p-12 relative overflow-hidden"
        >
          <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-600/5 blur-3xl rounded-full" />
          
          <div className="text-center mb-8">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Need dedicated assistance?</h2>
            <p className="text-gray-400 text-sm mt-2">Our technical operations division is on standby to resolve integration, billing, or security queries.</p>
          </div>

          {contactSuccess && (
            <div className="mb-6 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 p-4 rounded-xl text-xs flex items-center gap-2.5">
              <CheckCircle2 className="w-5 h-5" />
              <span>Your request has been received. Our operations team will respond to your registered email shortly.</span>
            </div>
          )}

          <form onSubmit={handleContactSubmit} className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-semibold text-gray-400 mb-1.5">Full Name</label>
                <input 
                  type="text" 
                  value={contactForm.name}
                  onChange={e => setContactForm({...contactForm, name: e.target.value})}
                  placeholder="e.g. Alexis Carter" 
                  className="w-full bg-[#080a0e] border border-[#232a39] rounded-lg px-4 py-2.5 text-sm text-white focus:outline-none focus:border-indigo-500 transition-colors"
                  required
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-gray-400 mb-1.5">Email Address</label>
                <input 
                  type="email" 
                  value={contactForm.email}
                  onChange={e => setContactForm({...contactForm, email: e.target.value})}
                  placeholder="alexis@example.com" 
                  className="w-full bg-[#080a0e] border border-[#232a39] rounded-lg px-4 py-2.5 text-sm text-white focus:outline-none focus:border-indigo-500 transition-colors"
                  required
                />
              </div>
            </div>
            <div>
              <label className="block text-xs font-semibold text-gray-400 mb-1.5">Inquiry Details</label>
              <textarea 
                rows={4} 
                value={contactForm.message}
                onChange={e => setContactForm({...contactForm, message: e.target.value})}
                placeholder="How can we assist you with VPS node routing, EA activation, or enterprise billing?" 
                className="w-full bg-[#080a0e] border border-[#232a39] rounded-lg px-4 py-2.5 text-sm text-white focus:outline-none focus:border-indigo-500 transition-colors resize-none"
                required
              />
            </div>
            <button 
              type="submit"
              className="w-full py-3 bg-indigo-600 text-white font-semibold text-xs tracking-wider rounded-lg hover:bg-indigo-500 transition shadow-lg shadow-indigo-600/10 uppercase"
            >
              Submit Ticket Details
            </button>
          </form>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[#1b202e] bg-[#07090d] py-12 text-center text-xs text-gray-500 relative z-10">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2">
            <Logo size="sm" onClick={() => onNavigate('/')} />
          </div>
          <div>
            &copy; 2026 Vinebot Systems Inc. All enterprise rights reserved.
          </div>
          <div className="flex flex-wrap justify-center gap-4 text-[11px] text-gray-500 font-mono">
            <span onClick={() => onNavigate('/terms')} className="hover:text-gray-300 transition cursor-pointer uppercase">Terms of Use</span>
            <span>&bull;</span>
            <span onClick={() => onNavigate('/privacy')} className="hover:text-gray-300 transition cursor-pointer uppercase">Privacy Policy</span>
            <span>&bull;</span>
            <span onClick={() => onNavigate('/cookie-policy')} className="hover:text-gray-300 transition cursor-pointer uppercase">Cookie Policy</span>
            <span>&bull;</span>
            <span onClick={() => onNavigate('/risk-disclosure')} className="hover:text-gray-300 transition cursor-pointer text-red-400 hover:text-red-300 uppercase font-bold">MT5 Risk Statement</span>
          </div>
        </div>
      </footer>

      {/* Cookie Consent Banner */}
      {showCookieConsent && (
        <div className="fixed bottom-0 left-0 right-0 z-50 p-4 sm:p-6 bg-[#0e1118]/95 backdrop-blur-md border-t border-[#1b202e] shadow-2xl transition-all duration-300">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="space-y-1 text-left md:max-w-3xl">
              <p className="text-xs text-gray-300 leading-relaxed">
                We use cookies to secure sessions and analyze platform traffic. By using Vinebot, you consent to our security token cookies used for authentication protection. 
                <span onClick={() => onNavigate('/cookie-policy')} className="text-indigo-400 hover:underline cursor-pointer ml-1 font-semibold">Cookie Policy</span>.
              </p>
              {showCookieSettingsInfo && (
                <div className="bg-[#080a0e] p-3 rounded-lg border border-white/5 text-[10px] text-gray-400 mt-2 space-y-1 font-mono">
                  <p className="font-bold text-gray-300">Active Cookies on Vinebot:</p>
                  <p>&bull; <span className="text-indigo-400">token</span> (Secure JWT): Session authentication. Mandatory for security.</p>
                  <p>&bull; <span className="text-indigo-400">refreshToken</span> (Secure JWT): Extended persistence. Optional but recommended.</p>
                </div>
              )}
            </div>
            <div className="flex gap-3 shrink-0">
              <button 
                onClick={() => setShowCookieSettingsInfo(!showCookieSettingsInfo)} 
                className="px-4 py-2 bg-white/5 hover:bg-white/10 text-white font-semibold text-[10px] tracking-wider rounded-lg uppercase cursor-pointer border border-white/10 transition"
              >
                Cookie Settings
              </button>
              <button 
                onClick={handleAcceptCookies} 
                className="px-5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-[10px] tracking-wider rounded-lg uppercase cursor-pointer transition shadow-lg shadow-indigo-600/10"
              >
                Accept All
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
