/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { useAuth } from './AuthContext';
import { 
  CreditCard, CheckCircle2, AlertTriangle, RefreshCw, 
  PlusCircle, ShieldCheck, DollarSign, ArrowRight, Zap, Ban, RotateCcw,
  ArrowLeft, Lock, HelpCircle, Sparkles, Crown
} from 'lucide-react';
import { UserSubscription, Payment, SubscriptionPlan } from '../types';

const DEFAULT_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-premium-month',
    name: 'PREMIUM ACCESS',
    description: 'Standard automated MetaTrader 5 bot deployment with dedicated VPS hosting.',
    price: 100.00,
    interval: 'month',
    features: [
      'Up to 3 Linked MT5 Accounts',
      'Standard Drawdown Safeguards',
      'Dedicated VPS Hosting Included',
      'Low-Latency Execution',
      'Standard Support'
    ],
    stripePriceId: 'price_premium_monthly'
  },
  {
    id: 'plan-vip-month',
    name: 'VIP UNLIMITED',
    description: 'Unlimited bot access. 20% profit-sharing fee applies to trading profits generated by the bot.',
    price: 200.00,
    interval: 'month',
    features: [
      'Unlimited Linked MT5 Accounts',
      'Custom High-Frequency Bot Strategies',
      'Dedicated High-Priority VPS',
      '20% Monthly Profit Share Settlement Agreement',
      '1-on-1 VIP Setup & Telegram Priority Support'
    ],
    stripePriceId: 'price_vip_monthly'
  }
];

export const SubscriptionCard: React.FC = () => {
  const { state, apiRequest: authApiRequest } = useAuth();
  
  const [plans, setPlans] = useState<SubscriptionPlan[]>(DEFAULT_PLANS);
  const [sub, setSub] = useState<UserSubscription | null>(null);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [loading, setLoading] = useState(true);
  const [processing, setProcessing] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error', text: string } | null>(null);
  const [loadingPlanId, setLoadingPlanId] = useState<string | null>(null);

  // Simulated Stripe Sandbox Checkout States
  const [checkoutPlan, setCheckoutPlan] = useState<SubscriptionPlan | null>(null);
  const [cardName, setCardName] = useState('');
  const [cardNumber, setCardNumber] = useState('4242 4242 4242 4242');
  const [cardExpiry, setCardExpiry] = useState('12/28');
  const [cardCvc, setCardCvc] = useState('424');
  const [cardZip, setCardZip] = useState('10001');
  const [checkoutStep, setCheckoutStep] = useState<'form' | 'processing' | 'success'>('form');
  const [checkoutError, setCheckoutError] = useState<string | null>(null);

  const fetchData = async () => {
    setLoading(true);
    try {
      let plansRes = await authApiRequest<SubscriptionPlan[]>('/api/subscription-plans');
      if (!plansRes.success || !plansRes.data || plansRes.data.length === 0) {
        plansRes = await authApiRequest<SubscriptionPlan[]>('/api/plans');
      }

      const historyRes = await authApiRequest<Payment[]>('/api/payments/history');

      if (plansRes.success && plansRes.data && plansRes.data.length > 0) {
        setPlans(plansRes.data);
      } else {
        setPlans(DEFAULT_PLANS);
      }
      if (historyRes.success && historyRes.data) {
        setPayments(historyRes.data);
      }

      // Fetch subscription from backend
      const subRes = await authApiRequest<UserSubscription | null>('/api/payments/subscription');
      if (subRes.success && subRes.data) {
        setSub(subRes.data);
      } else {
        setSub(null);
      }
    } catch (e) {
      console.error(e);
      setPlans(DEFAULT_PLANS);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [state.user]);

  const handleInitiateCheckout = async (plan: SubscriptionPlan) => {
    if (processing) return;
    setLoadingPlanId(plan.id);
    setProcessing(true);
    setCheckoutError(null);

    try {
      const res = await authApiRequest<{ checkoutUrl: string }>('/api/stripe/create-checkout-session', {
        method: 'POST',
        body: JSON.stringify({ planId: plan.id })
      });

      if (res.success && res.data?.checkoutUrl) {
        const url = res.data.checkoutUrl;
        if (url.startsWith('http') && url.includes('stripe.com')) {
          window.location.href = url;
          return;
        }
      }
    } catch (err: any) {
      console.warn('Stripe checkout API pending or keys missing, falling back to Sandbox checkout UI:', err);
    } finally {
      setProcessing(false);
      setLoadingPlanId(null);
    }

    setCheckoutPlan(plan);
    setCardName(state.user?.name || '');
    setCheckoutStep('form');
    setCheckoutError(null);
  };

  const handleConfirmCheckout = async (e: React.FormEvent) => {
    e.preventDefault();
    if (processing) return;

    if (!cardName.trim()) {
      setCheckoutError('Please enter the cardholder name.');
      return;
    }

    setCheckoutStep('processing');
    setProcessing(true);
    setCheckoutError(null);

    // Simulated Stripe Sandbox authorization handshake
    await new Promise(resolve => setTimeout(resolve, 1800));

    try {
      const res = await authApiRequest('/api/payments/checkout', {
        method: 'POST',
        body: JSON.stringify({ planId: checkoutPlan!.id })
      });

      if (res.success) {
        setCheckoutStep('success');
        setTimeout(() => {
          setCheckoutPlan(null);
          setMessage({ 
            type: 'success', 
            text: `Payment authorized via Stripe Sandbox. Automated license subscription to "${checkoutPlan!.name}" is now fully ACTIVE.` 
          });
          fetchData();
        }, 2200);
      } else {
        setCheckoutError(res.message || 'Payment authorization failed.');
        setCheckoutStep('form');
      }
    } catch (err: any) {
      setCheckoutError(err.message || 'An unexpected connection error occurred.');
      setCheckoutStep('form');
    } finally {
      setProcessing(false);
    }
  };

  const handleCancelSub = async () => {
    if (!window.confirm('Are you sure you want to schedule cancellation of your automated bot subscription? The bot will turn off at the end of the active billing term.')) {
      return;
    }

    setProcessing(true);
    setMessage(null);

    const res = await authApiRequest('/api/payments/cancel-subscription', {
      method: 'POST'
    });

    if (res.success) {
      setMessage({ type: 'success', text: 'Auto-renew disabled. Subscription scheduled for cancellation.' });
      fetchData();
    } else {
      setMessage({ type: 'error', text: res.message });
    }
    setProcessing(false);
  };

  const handleResumeSub = async () => {
    setProcessing(true);
    setMessage(null);

    const res = await authApiRequest('/api/payments/resume-subscription', {
      method: 'POST'
    });

    if (res.success) {
      setMessage({ type: 'success', text: 'Auto-renew successfully re-enabled!' });
      fetchData();
    } else {
      setMessage({ type: 'error', text: res.message });
    }
    setProcessing(false);
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-6 w-48 bg-white/5 rounded animate-pulse" />
        <div className="h-96 bg-white/5 rounded-xl animate-pulse" />
      </div>
    );
  }

  // --- RENDERING INTEGRATED MOCK STRIPE CHECKOUT ---
  if (checkoutPlan) {
    return (
      <div className="max-w-4xl mx-auto space-y-6 animate-fade-in" id="stripe-checkout-sandbox-container">
        
        {/* Sandbox Top Warning Belt */}
        <div className="bg-yellow-500/10 border border-yellow-500/25 p-3.5 rounded-xl text-yellow-400 text-xs flex items-center justify-between gap-3 shadow-lg shadow-yellow-500/5">
          <div className="flex items-center gap-2.5">
            <ShieldCheck className="w-5 h-5 animate-pulse text-yellow-400" />
            <div>
              <span className="font-bold">Stripe Sandbox Node Active:</span> You are currently using our integrated high-fidelity secure checkout flow simulator. Do not enter real credentials.
            </div>
          </div>
          <button 
            onClick={() => setCheckoutPlan(null)}
            className="text-yellow-400/60 hover:text-yellow-400 font-bold transition-colors uppercase text-[10px] tracking-wider cursor-pointer"
          >
            Cancel Payment
          </button>
        </div>

        {/* Back Button */}
        <div>
          <button 
            onClick={() => setCheckoutPlan(null)}
            className="text-white/60 hover:text-white text-xs font-semibold flex items-center gap-2 transition-colors cursor-pointer group"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> Back to Billing Dashboard
          </button>
        </div>

        {/* Outer Split Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 bg-[#0b0e14] border border-[#1b202e] rounded-2xl overflow-hidden shadow-2xl">
          
          {/* Left Column: Product Info & Invoicing Summary (Stripe style) */}
          <div className="lg:col-span-5 bg-[#080a0e] border-r border-[#151a24] p-8 flex flex-col justify-between">
            <div className="space-y-8">
              <div>
                <p className="text-[11px] font-bold text-blue-400 font-mono tracking-widest uppercase">Vinebot Systems, Inc.</p>
                <h2 className="text-2xl font-extrabold text-white mt-2 tracking-tight">{checkoutPlan.name}</h2>
                <p className="text-white/40 text-xs mt-1 leading-relaxed">{checkoutPlan.description}</p>
              </div>

              {/* Price Tag */}
              <div className="flex items-baseline gap-1.5 py-4 border-y border-[#151a24]">
                <span className="text-3xl font-extrabold text-white">${checkoutPlan.price.toFixed(2)}</span>
                <span className="text-white/40 text-xs">/ {checkoutPlan.interval}</span>
              </div>

              {/* Line Items Invoice details */}
              <div className="space-y-3.5 text-xs">
                <div className="flex justify-between text-white/60">
                  <span>Vinebot Bot Licence (1 Month)</span>
                  <span className="text-white">${checkoutPlan.price.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-white/40 text-[11px]">
                  <span>Setup Fees & Node Provisioning</span>
                  <span className="text-emerald-400">FREE</span>
                </div>
                <div className="flex justify-between text-white/40 text-[11px]">
                  <span>Sales Tax (0.00%)</span>
                  <span>$0.00</span>
                </div>
                <div className="flex justify-between text-white font-bold border-t border-[#151a24] pt-4 text-sm">
                  <span>Total Due Today</span>
                  <span className="text-blue-400">${checkoutPlan.price.toFixed(2)}</span>
                </div>
              </div>
            </div>

            {/* Security SSL Footer note */}
            <div className="mt-12 flex items-center gap-2.5 text-[10px] text-white/30 border-t border-[#151a24] pt-4">
              <Lock className="w-3.5 h-3.5" />
              <span>TLS 1.3 / AES-256 Bit Secure Payment Processing</span>
            </div>
          </div>

          {/* Right Column: Simulated Card payment Form */}
          <div className="lg:col-span-7 p-8 flex flex-col justify-between">
            {checkoutStep === 'form' && (
              <form onSubmit={handleConfirmCheckout} className="space-y-6" id="mock-stripe-form">
                <div>
                  <h3 className="text-sm font-bold text-white tracking-tight">Enter Payment Details</h3>
                  <p className="text-white/40 text-[10px] mt-0.5">Please fill out any mock credentials to complete purchase authorization.</p>
                </div>

                {checkoutError && (
                  <div className="p-3.5 bg-red-500/10 border border-red-500/25 rounded-xl text-xs text-red-400 flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4 shrink-0" />
                    <span>{checkoutError}</span>
                  </div>
                )}

                <div className="space-y-4">
                  {/* Lock Email Address (readonly prefilled) */}
                  <div>
                    <label className="block text-[10px] font-bold text-white/55 uppercase tracking-wider mb-1.5">Email Address</label>
                    <input 
                      type="email" 
                      value={state.user?.email || ''} 
                      readOnly 
                      className="w-full bg-[#121620]/50 border border-[#1b202e] rounded-lg px-3.5 py-2.5 text-xs text-white/50 focus:outline-none cursor-not-allowed"
                    />
                  </div>

                  {/* Simulated Card Info */}
                  <div>
                    <label className="block text-[10px] font-bold text-white/55 uppercase tracking-wider mb-1.5">Card Information</label>
                    <div className="bg-[#080a0e] border border-[#1b202e] focus-within:border-blue-500 rounded-lg overflow-hidden transition-colors">
                      <div className="flex items-center px-3.5 py-2.5 border-b border-[#1b202e]">
                        <CreditCard className="w-4 h-4 text-white/40 mr-2.5 shrink-0" />
                        <input 
                          type="text" 
                          placeholder="Card number"
                          value={cardNumber}
                          onChange={(e) => setCardNumber(e.target.value)}
                          className="w-full bg-transparent text-xs text-white placeholder-white/20 focus:outline-none"
                        />
                      </div>
                      <div className="flex divide-x divide-[#1b202e]">
                        <div className="w-1/2 px-3.5 py-2.5">
                          <input 
                            type="text" 
                            placeholder="MM / YY"
                            value={cardExpiry}
                            onChange={(e) => setCardExpiry(e.target.value)}
                            className="w-full bg-transparent text-xs text-white placeholder-white/20 focus:outline-none"
                          />
                        </div>
                        <div className="w-1/2 px-3.5 py-2.5">
                          <input 
                            type="text" 
                            placeholder="CVC"
                            value={cardCvc}
                            onChange={(e) => setCardCvc(e.target.value)}
                            className="w-full bg-transparent text-xs text-white placeholder-white/20 focus:outline-none"
                          />
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Cardholder Name */}
                  <div>
                    <label className="block text-[10px] font-bold text-white/55 uppercase tracking-wider mb-1.5">Cardholder Name</label>
                    <input 
                      type="text" 
                      placeholder="Jane Doe"
                      value={cardName} 
                      onChange={(e) => setCardName(e.target.value)}
                      required
                      className="w-full bg-[#080a0e] border border-[#1b202e] focus:border-blue-500 rounded-lg px-3.5 py-2.5 text-xs text-white placeholder-white/25 focus:outline-none transition-colors"
                    />
                  </div>

                  {/* Country/ZIP */}
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-[10px] font-bold text-white/55 uppercase tracking-wider mb-1.5">Country or region</label>
                      <select className="w-full bg-[#080a0e] border border-[#1b202e] rounded-lg px-3.5 py-2.5 text-xs text-white focus:outline-none transition-colors cursor-pointer">
                        <option>United States</option>
                        <option>United Kingdom</option>
                        <option>Canada</option>
                        <option>Nigeria</option>
                        <option>Germany</option>
                        <option>South Africa</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-[10px] font-bold text-white/55 uppercase tracking-wider mb-1.5">Postal Code / ZIP</label>
                      <input 
                        type="text" 
                        placeholder="10001"
                        value={cardZip} 
                        onChange={(e) => setCardZip(e.target.value)}
                        className="w-full bg-[#080a0e] border border-[#1b202e] focus:border-blue-500 rounded-lg px-3.5 py-2.5 text-xs text-white placeholder-white/25 focus:outline-none transition-colors"
                      />
                    </div>
                  </div>
                </div>

                <div className="pt-2">
                  <button
                    type="submit"
                    disabled={processing}
                    className="w-full py-3.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold tracking-wider uppercase shadow-lg shadow-blue-600/15 transition-all flex items-center justify-center gap-2 cursor-pointer"
                  >
                    <Lock className="w-3.5 h-3.5" /> Pay ${checkoutPlan.price.toFixed(2)} Securely
                  </button>
                </div>
              </form>
            )}

            {/* Checkout processing State */}
            {checkoutStep === 'processing' && (
              <div className="h-full flex flex-col items-center justify-center py-20 text-center animate-fade-in" id="mock-stripe-processing">
                <div className="relative mb-6">
                  <div className="w-16 h-16 rounded-full border-2 border-blue-500/20 border-t-2 border-t-blue-500 animate-spin" />
                  <Lock className="w-5 h-5 text-blue-400 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
                </div>
                <h3 className="text-base font-bold text-white tracking-tight">Authorizing Payment</h3>
                <p className="text-white/40 text-[10px] max-w-xs mt-2.5 leading-relaxed">
                  Executing instant Secure SSL Handshake with Stripe Sandbox Nodes. Please do not close or reload this dashboard tab...
                </p>
              </div>
            )}

            {/* Checkout Success Screen */}
            {checkoutStep === 'success' && (
              <div className="h-full flex flex-col items-center justify-center py-20 text-center animate-fade-in" id="mock-stripe-success">
                <div className="w-16 h-16 bg-emerald-500/10 border border-emerald-500/25 rounded-full flex items-center justify-center mb-6 shadow-lg shadow-emerald-500/5">
                  <CheckCircle2 className="w-8 h-8 text-emerald-400 animate-bounce" />
                </div>
                <h3 className="text-base font-bold text-white tracking-tight">Payment Authorized!</h3>
                <p className="text-emerald-400 text-xs font-mono mt-1 font-bold">STRIPE_SETTLEMENT_SUCCESS</p>
                <p className="text-white/40 text-[10px] max-w-xs mt-3 leading-relaxed">
                  Sandbox payment verified and settled successfully. We are provisioning your automated low-latency VPS nodes now.
                </p>
              </div>
            )}

            {/* Powered by stripe line */}
            <div className="pt-6 border-t border-[#151a24] text-[10px] text-white/20 flex items-center justify-between">
              <span>Secure Checkout Powered by Stripe</span>
              <div className="flex gap-3">
                <a href="#" onClick={(e) => e.preventDefault()} className="hover:text-white/40">Terms</a>
                <a href="#" onClick={(e) => e.preventDefault()} className="hover:text-white/40">Privacy Policy</a>
              </div>
            </div>
          </div>

        </div>
      </div>
    );
  }

  // --- STANDARD DASHBOARD VIEW ---
  const activePlans = plans && plans.length > 0 ? plans : DEFAULT_PLANS;
  const activePlan = activePlans.find(p => p.id === sub?.planId);

  return (
    <div className="space-y-10 animate-fade-in" id="subscription-card-view">
      
      {/* Header Info */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-3">
          <CreditCard className="w-6 h-6 text-blue-400" /> Billing & Subscription Center
        </h1>
        <p className="text-white/40 text-xs mt-1">
          Select or update your automated trading license and inspect payment histories.
        </p>
      </div>

      {message && (
        <div className={`p-4 rounded-xl text-xs flex items-center gap-2.5 ${
          message.type === 'success' 
            ? 'bg-emerald-500/10 border border-emerald-500/25 text-emerald-400' 
            : 'bg-red-500/10 border border-red-500/25 text-red-400'
        }`}>
          {message.type === 'success' ? <CheckCircle2 className="w-5 h-5 shrink-0" /> : <AlertTriangle className="w-5 h-5 shrink-0" />}
          <span>{message.text}</span>
        </div>
      )}

      {/* Grid: Left - Active Subscription, Right - Pricing Options */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Active Subscription Details (Column 1) */}
        <div className="lg:col-span-1 space-y-6">
          <div className="glass-card p-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/5 blur-2xl rounded-full" />
            <h2 className="text-xs font-bold text-white/40 uppercase tracking-widest border-b border-white/5 pb-3 mb-4">
              Licence Agreement
            </h2>

            {sub ? (
              <div className="space-y-4">
                <div>
                  <p className="text-[10px] text-blue-400 font-bold uppercase tracking-wider font-mono">Selected Plan</p>
                  <p className="text-xl font-extrabold text-white mt-1 tracking-tight">{activePlan?.name || 'Vinebot Pro Access'}</p>
                </div>

                <div className="flex justify-between text-xs py-2 border-y border-white/5">
                  <span className="text-white/40 font-semibold">Status:</span>
                  <div className="flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                    <span className="font-bold text-emerald-400 font-mono text-[10px] uppercase">Active</span>
                  </div>
                </div>

                <div className="flex justify-between text-xs py-2">
                  <span className="text-white/40 font-semibold">Stripe ID:</span>
                  <span className="font-mono text-white/60 text-[10px]">{sub.stripeSubscriptionId}</span>
                </div>

                <div className="flex justify-between text-xs py-2 border-b border-white/5">
                  <span className="text-white/40 font-semibold">Renewal Period:</span>
                  <span className="font-medium text-white text-[10px]">
                    {new Date(sub.currentPeriodEnd).toLocaleDateString()}
                  </span>
                </div>

                {sub.cancelAtPeriodEnd ? (
                  <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-3 text-[10px] text-amber-400 leading-relaxed">
                    Auto-renew is disabled. Your trading VPS will stand-down on {new Date(sub.currentPeriodEnd).toLocaleDateString()}.
                  </div>
                ) : (
                  <div className="bg-white/5 border border-white/10 rounded-lg p-3 text-[10px] text-white/60 leading-relaxed">
                    Subscription renews automatically monthly. Payments are debited securely from card vault.
                  </div>
                )}

                <div className="pt-2">
                  {sub.cancelAtPeriodEnd ? (
                    <button
                      onClick={handleResumeSub}
                      disabled={processing}
                      className="w-full py-2.5 bg-emerald-600/10 hover:bg-emerald-600 text-emerald-400 hover:text-white border border-emerald-500/20 hover:border-emerald-500 rounded-lg text-[10px] font-bold tracking-wide uppercase flex items-center justify-center gap-1.5 cursor-pointer"
                    >
                      <RotateCcw className="w-3.5 h-3.5" /> Resume Auto-Renew
                    </button>
                  ) : (
                    <button
                      onClick={handleCancelSub}
                      disabled={processing}
                      className="w-full py-2.5 bg-red-500/10 hover:bg-red-500 text-red-400 hover:text-white border border-red-500/20 hover:border-red-500 rounded-lg text-[10px] font-bold tracking-wide uppercase flex items-center justify-center gap-1.5 cursor-pointer"
                    >
                      <Ban className="w-3.5 h-3.5" /> Disable Auto-Renew
                    </button>
                  )}
                </div>
              </div>
            ) : (
              <div className="py-6 px-4 text-center space-y-4 rounded-xl bg-amber-500/5 border border-amber-500/10" id="licence-no-active-alert">
                <div className="w-10 h-10 rounded-full bg-amber-500/10 flex items-center justify-center mx-auto">
                  <AlertTriangle className="w-5 h-5 text-amber-500 animate-pulse" />
                </div>
                <div className="space-y-1">
                  <p className="text-xs font-bold text-amber-400 uppercase tracking-wider font-mono">No Active License</p>
                  <p className="text-[10px] text-white/60 leading-relaxed">
                    Your automated cloud bot is currently <span className="text-rose-400 font-bold">DEACTIVATED</span>.
                  </p>
                </div>
                <p className="text-[10px] text-white/40 leading-relaxed bg-[#080a0e]/60 p-2.5 rounded-lg border border-white/5">
                  Please select a plan from <span className="text-blue-400 font-semibold uppercase font-mono text-[9px]">"Change Plan Options"</span> to activate your high-frequency cloud bot.
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Pricing Selection Grid (Column 2-3) */}
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-card p-6">
            <h2 className="text-sm font-bold text-white uppercase tracking-wider mb-6 pb-3 border-b border-white/5">
              Change Plan Options
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6" id="pricing-plans-grid">
              {activePlans.map((p) => {
                const isCurrent = sub?.planId === p.id;
                const isLoading = loadingPlanId === p.id;
                const isVip = p.id === 'plan-vip-month' || p.name.toUpperCase().includes('VIP');

                return (
                  <div 
                    key={p.id}
                    className={`border rounded-xl p-5 flex flex-col justify-between relative transition-all duration-200 ${
                      isVip
                        ? 'border-amber-500/50 bg-gradient-to-b from-amber-500/10 via-white/5 to-white/5 shadow-xl shadow-amber-500/10'
                        : isCurrent
                          ? 'border-blue-500 bg-white/10 shadow-lg shadow-blue-500/5'
                          : 'border-white/10 bg-white/5 hover:border-white/20'
                    }`}
                  >
                    {isVip && (
                      <div className="absolute -top-3.5 right-4 bg-gradient-to-r from-amber-500 via-amber-400 to-amber-600 text-black font-extrabold text-[9px] tracking-widest uppercase px-3 py-1 rounded-full shadow-lg shadow-amber-500/25 border border-amber-300/40 flex items-center gap-1.5 z-10">
                        <Sparkles className="w-3 h-3 text-black fill-black" /> MOST POPULAR / VIP
                      </div>
                    )}

                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        {isVip && <Crown className="w-4 h-4 text-amber-400" />}
                        <h3 className={`text-xs font-bold uppercase tracking-wider ${isVip ? 'text-amber-400' : 'text-white'}`}>
                          {p.name}
                        </h3>
                      </div>
                      <p className="text-[10px] text-white/60 leading-relaxed mb-4 min-h-[32px]">{p.description}</p>
                      
                      <div className="mb-4">
                        <div className="flex items-baseline">
                          <span className="text-3xl font-extrabold text-white">${p.price}</span>
                          <span className="text-white/40 text-xs ml-1.5">/ {p.interval}</span>
                        </div>
                        {isVip && (
                          <div className="mt-1.5 inline-flex items-center gap-1 text-amber-400 font-extrabold text-[10px] tracking-wider font-mono uppercase bg-amber-500/10 px-2 py-0.5 rounded border border-amber-500/20">
                            + 20% Profit Share
                          </div>
                        )}
                      </div>

                      <ul className="space-y-2.5 border-t border-white/5 pt-4 mb-6">
                        {p.features.map((f, idx) => (
                          <li key={idx} className="flex items-start gap-2 text-[10px] text-white/70">
                            <CheckCircle2 className={`w-3.5 h-3.5 mt-0.5 shrink-0 ${isVip ? 'text-amber-400' : 'text-blue-400'}`} />
                            <span>{f}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    <button
                      id={`sub-action-${p.id}`}
                      onClick={() => handleInitiateCheckout(p)}
                      disabled={isCurrent || processing}
                      className={`w-full py-2.5 rounded-lg text-[10px] font-bold tracking-wide uppercase transition-all flex items-center justify-center gap-1.5 ${
                        isCurrent 
                          ? 'bg-blue-600/10 text-blue-400 border border-blue-500/20' 
                          : isLoading
                            ? 'bg-blue-600/50 text-white/80 cursor-wait'
                            : isVip
                              ? 'bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-black font-extrabold shadow-lg shadow-amber-500/20 cursor-pointer'
                              : 'bg-blue-600 text-white hover:bg-blue-500 shadow-md shadow-blue-600/10 cursor-pointer'
                      }`}
                    >
                      {isLoading && <RefreshCw className="w-3.5 h-3.5 animate-spin" />}
                      {isCurrent ? 'Current License Active' : isLoading ? 'Redirecting to Checkout...' : 'Subscribe / Select Plan'}
                    </button>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

      </div>

      {/* Billing history Section */}
      <div className="glass-card p-6">
        <h2 className="text-sm font-bold text-white uppercase tracking-wider mb-1">Billing history</h2>
        <p className="text-white/40 text-[10px] mb-4 pb-3 border-b border-white/5">Invoice copies and transaction settlement receipts.</p>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs divide-y divide-white/5">
            <thead>
              <tr className="text-white/40 font-bold uppercase tracking-wider text-[10px]">
                <th className="py-3 px-4">Receipt ID</th>
                <th className="py-3 px-4">Billing Date</th>
                <th className="py-3 px-4">Amount</th>
                <th className="py-3 px-4">Stripe Intent</th>
                <th className="py-3 px-4">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5 text-white/80">
              {payments.length === 0 ? (
                <tr>
                  <td colSpan={5} className="py-8 text-center text-white/40">No payment receipts found.</td>
                </tr>
              ) : (
                payments.map((p) => (
                  <tr key={p.id} className="hover:bg-white/5">
                    <td className="py-3.5 px-4 font-mono text-[10px] text-blue-400">{p.id.substring(0, 8)}</td>
                    <td className="py-3.5 px-4 text-[10px]">{new Date(p.createdAt).toLocaleDateString()}</td>
                    <td className="py-3.5 px-4 font-bold font-sans">${p.amount.toFixed(2)}</td>
                    <td className="py-3.5 px-4 font-mono text-[9px] text-white/40">{p.stripePaymentIntentId || 'N/A'}</td>
                    <td className="py-3.5 px-4">
                      <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-[9px] font-bold text-emerald-400 uppercase">
                        Succeeded
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
